/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.005']}
        position={[-0.153, 0.446, -0.393]}
        rotation={[-0.383, 0.547, -0.065]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={materials['Material.004']}
        position={[0.195, 0.609, -0.393]}
        rotation={[0.253, 0.324, -0.081]}
        scale={0.165}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.003']}
        position={[0.181, 0.147, -0.4]}
        rotation={[0.715, -0.648, 0.505]}
        scale={[0.096, 0.142, 0.096]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus.geometry}
        material={materials['Material.002']}
        position={[0, -0.324, -0.393]}
        rotation={[0.686, -0.39, 0.458]}
        scale={0.208}
      />
    </group>
  )
}

useGLTF.preload('/room.glb')
